COURSES = [
 {
  "id": 1,
  "name": "Data analysis",
  "link": "https://fr.linkedin.com/learning/topics/analyse-de-donnees?trk=learning-topics_aside-topics&upsellOrderOrigin=default_guest_learning",
  "domains": "Business",
  "description": "Learn the latest quantitative and qualitative data analysis skills for effective business decision-making and explore the necessary tools, such as Microsoft Excel, Tableau, SQL, Python, R, and more.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 2,
  "name": "Business analyse",
  "link": "https://fr.linkedin.com/learning/topics/analyse-metier?trk=learning-ntopics_aside-topics&upsellOrderOrigin=default_guest_learning",
  "domains": "Business/Office tools and software",
  "description": "Enhance your business analysis skills with expert-led courses on critical thinking, business analytics, project management, requirements gathering, and data presentation.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 3,
  "name": "Business analyse and strategy",
  "link": "https://fr.linkedin.com/learning/topics/strategie-et-analyse-metier?trk=learning-topics_aside-topics&upsellOrderOrigin=default_guest_learning",
  "domains": "Business",
  "description": "",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 4,
  "name": "Business",
  "link": "https://fr.linkedin.com/learning/topics/business-2?trk=learning-topics_asiden-topics&upsellOrderOrigin=default_guest_learning",
  "domains": "Business",
  "description": "The Business library is a better business school for professionals. It teaches you how to manage time and projects; be more productive with business software and technology; and lead yourself, others, and the business across functions and over the span of your career.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 5,
  "name": "Entrepreneurship",
  "link": "https://fr.linkedin.com/learning/topics/entrepreneuriat?trk=learning-topicsn_aside-topics&upsellOrderOrigin=default_guest_learning&original_referern=https%3A%2F%2Ffr.linkedin.com%2Flearning%2Ftopics%2Fanalyse-de-ndonnees%3Ftrk%3Dlearning-topics_aside-topics%26upsellOrderOrigin%3Dndefault_guest_learning",
  "domains": "Business",
  "description": "Get the training you need to stay ahead with expert-led courses on Entrepreneurship.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 6,
  "name": "Business intellligence",
  "link": "https://fr.linkedin.com/learning/topics/informatique-decisionnelle?trk=nlearning-topics_aside-topics&upsellOrderOrigin=default_guest_learning",
  "domains": "Business",
  "description": "Get the training you need to stay ahead with expert-led courses on Business Intelligence.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 7,
  "name": "career developpement",
  "link": "https://fr.linkedin.com/learning/topics/developpement-de-carrieren-16111848?trk=learning-topics_aside-topics&upsellOrderOrigin=defaultn_guest_learning",
  "domains": "General culture",
  "description": "Learn how to manage your career, from your first job search to moving up in your career to switching careers. Get the skills you need to grow your network, write a resume, interview, get a job, and get promoted.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 8,
  "name": "Human ressources",
  "link": "https://fr.linkedin.com/learning/topics/ressources-humaines-1611702n6?trk=learning-topics_aside-topics&upsellOrderOrigin=default_guest_nlearning",
  "domains": "Human ressource",
  "description": "Learn how to be an effective HR professional, whether generalist or specialist. Acquire needed skills in talent management, recruiting, compensation and benefits, hiring, L&D, employee relations, HR strategy, and more.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 9,
  "name": "Marketing",
  "link": "https://fr.linkedin.com/learning/topics/marketing-3?trk=learning-topicsn_aside-topics&upsellOrderOrigin=default_guest_learning",
  "domains": "Business",
  "description": "Find your marketing niche, or learn it all— branding, PR, SEO, analytics, social media, and email marketing. Learn how to develop, implement, and measure a winning marketing strategy using today's best tools.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 10,
  "name": "Cloud computing",
  "link": "https://fr.linkedin.com/learning/topics/cloud-computing?trk=learningn-topics_aside-topics&upsellOrderOrigin=default_guest_learning",
  "domains": "Technologie/System and network administration",
  "description": "Get the training you need to stay ahead with expert-led courses on Cloud Computing.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 11,
  "name": "DevOps basic",
  "link": "https://fr.linkedin.com/learning/topics/bases-du-devops?trk=learningn-topics_aside-topics&upsellOrderOrigin=default_guest_learning&originaln_referer=https%3A%2F%2Ffr.linkedin.com%2Flearning%2Ftopics%2Fncloud-computing%3Ftrk%3Dlearning-topics_aside-topics%26upsellOrdernOrigin%3Ddefault_guest_learning",
  "domains": "Technologie/DecOps",
  "description": "Optimize the speed and reliability of your software releases. Learn about DevOps culture, processes, and tools, as well as practical techniques for infrastructure automation, continuous delivery, SRE, and more.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 12,
  "name": "Data science",
  "link": "https://fr.linkedin.com/learning/topics/data-science-16113699?trk=learnning-topics_aside-topics&upsellOrderOrigin=default_guest_learning",
  "domains": "Technologie/Data science",
  "description": "Data science is one of today's top careers. Get the training you need to get ahead—or stay on top—in fields such as data analysis, mining, visualization, and big data, using tools like Excel, R, Hadoop, and Python.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 13,
  "name": "Software developpement",
  "link": "https://fr.linkedin.com/learning/topics/developpement-logiciel?trnk=learning-topics_aside-topics&upsellOrderOrigin=default_guest_learning",
  "domains": "Technologie/Software developpement",
  "description": "Whether you want to learn a new language, develop your firstn application or an enterprise database, we have the training nyou need to advance your career.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 14,
  "name": "Database management",
  "link": "https://fr.linkedin.com/learning/topics/gestion-des-bases-de-donnees?trkn=learning-topics_aside-topics&upsellOrderOrigin=default_guest_learning",
  "domains": "Technologie/Database management",
  "description": "Get the training you need to stay ahead with expert-led courses on Database Management.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 15,
  "name": "Help desk IT",
  "link": "https://fr.linkedin.com/learning/topics/help-desk-it-16114571?trk=learningn-topics_aside-topics&upsellOrderOrigin=default_guest_learning",
  "domains": "Technologie/Help desk IT",
  "description": "Get the training you need to stay ahead with expert-led courses on IT Help Desk.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 16,
  "name": "Security",
  "link": "https://fr.linkedin.com/learning/topics/securite?trk=learning-topics_aside-ntopics&upsellOrderOrigin=default_guest_learning",
  "domains": "Technologie/Security",
  "description": "",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 17,
  "name": "System and network administration",
  "link": "https://fr.linkedin.com/learning/topics/operations-et-securite-informatiquesn?trk=learning-topics_aside-topics&upsellOrderOrigin=default_guest_learning",
  "domains": "Technologie/System and network administration",
  "description": "These IT training courses help you understand administration andn support tasks. Manage troubleshooting on Windows, Linux andn Mac. Configure and secure networks, servers and operating systems.",
  "offered_by": "",
  "type": "Course",
  "rating": "",
  "difficulty": "intermediate",
  "duration": "",
  "number_of_videos": "",
  "source": "Linkedin"
 },
 {
  "id": 18,
  "name": "Introduction to Relational Databases",
  "link": "https://www.youtube.com/watch?v=jReDVnyCNdQ&list=PLB9AbbTDeBzT9JN8-Ow669spvEN8DKAwp",
  "domains": "Technologie/Data",
  "description": "Introduction to databases course and tutorial.",
  "offered_by": "coursaline",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "5h 45min 01s",
  "number_of_videos": 28,
  "source": "Youtube"
 },
 {
  "id": 19,
  "name": "Full Database",
  "link": "https://www.youtube.com/watch?v=HXV3zeQKqGY",
  "domains": "Technologie/Data",
  "description": "The course is designed for beginners to SQL and database management systems, and will introduce common database management topics.nnThroughout the course we'll be looking at various topics including schema design, basic C.R.U.D operations, aggregation, nested queries, joins, keys and much more.nnYou can get PopSQL to follow along here: http://popsql.com/freecodecampnn🔗Company Database Code: https://www.giraffeacademy.com/databa...",
  "offered_by": "freeCodeCamp",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "4hr 20min 48s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 20,
  "name": "Business Intelligence Tutorial",
  "link": "https://youtu.be/Hg8zBJ1DhLQ",
  "domains": "Business/Business intelligence",
  "description": "In this Business Intelligence full course video, we’ll look at what is Businessn Intelligence, Who is a Business Intelligence expert, and various BI tools used.n We will look at each tool in detail.",
  "offered_by": "Simplilearn",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "9hr 18min 44s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 21,
  "name": "Software Development",
  "link": "https://www.youtube.com/watch?v=Ubg3PenEdNw&list=PLEiEAq2VkUUJfeP9bgWAEs-NbGJyYXc-v",
  "domains": "Technologie/Software Development",
  "description": "This software development course is a series of live sessions where we will understand in-depth concepts of Data Structures, algorithms in Data Structures, C++, Core Java, Advance Java, Python and JavaScript.",
  "offered_by": "Simplilearn",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "8 Days",
  "number_of_videos": 8,
  "source": "Youtube"
 },
 {
  "id": 22,
  "name": "Business Finance in Business Management",
  "link": "https://www.youtube.com/watch?v=gGE4GUv1-F0&list=PL1O57nCUQ-e-OVRFdIB-Gu1U91yH7egmm&index=2",
  "domains": "Business/Business management",
  "description": "Learn important aspects of business finance in business management.n10 major functions of financial management.nn1. Estimates capital requirements.n2. Ascertains capital compositions.n3. Makes choice of sources of funds.n4. Investment of total funds.n5. Disposal of surplus.n6. Manage cashflow.n7. Control finances.n8. Decisions of acquisitions.n9. Tax planning, protection of assets.n10. Decision on capital budgeting.",
  "offered_by": "Young Entrepreneur Forum",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "1hr 1min 21s",
  "number_of_videos": 21,
  "source": "Youtube"
 },
 {
  "id": 23,
  "name": "Business Analyst",
  "link": "https://youtu.be/Kye_heYF6bs",
  "domains": "Business/Business Analysis",
  "description": "This video on Business Analyst Training for Beginners explains all the fundamentals of Business Analysis & the roles & responsibilities of a Business AnalystnAreas covered:n1. History of Business Analysisn2. What is Business Analysis?n3. Importance of Business Analysisn4. Companies using Business Analysisn5. Business Analysis process & knowledge areasn6. Business Analysis case studyn7. Business Analysis techniquesn8. Roles & responsibilities of a Business Analystn9. Business Analyst skillsn10. Business Analysis tools & certificationsn11. Demo on Balsamiq tool",
  "offered_by": "Invensis Learning",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "1hr 1min 20s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 24,
  "name": "DevOps Tools",
  "link": "https://www.youtube.com/watch?v=12HwsqHoaE8&pp=ugMICgJmchABGAE%3D",
  "domains": "Technologie/DevOps",
  "description": "This comprehensive DevOps tools course will help you learn DevOps concepts, DevOps tools with examples and demonstrations ranging from basics to advanced. It will cover different DevOps tools like Git, Ansible, Selenium, Docker, Chef, Puppet, Kubernetes and Gradle.nnBelow are the topics covered in this video:nWhat is DevOpsnWhy DevOpsnDevOps stagesnWhat is Git?nWhat is GitHub?nGit commandsnWhat is JenkinsnJenkins PipelinenInstalling JenkinsnWhat is Docker?nInstalling DockernWhat is a Docker container?nWhat is Kubernetes?nKubernetes vs. DockernKubernetes on AWSnWhat is Marionette?nWhy puppet?nInstallation of puppetsnInstall AnsiblenWhat is Ansible?nAdvantages of AnsiblenWhat is seleniumnSelenium Tool SuitenInstallation of seleniumnDevOps Interview Questions",
  "offered_by": "Simplilearn",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "11hr 19min 23s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 25,
  "name": "Data Analytics",
  "link": "https://www.youtube.com/watch?v=CaqJ65CIoMw",
  "domains": "Business",
  "description": "Who should take up this course?nAspiring professionals of any educational background with an analytical frame of mind are best suited to pursue the Data Analyst Master’s Program, including:n1. IT professionalsn2. Banking and finance professionalsn3. Marketing managersn4. Sales professionalsn5. Supply chain network managersn6. Beginners in the data analytics domainn7. Students in UG/ PG programs",
  "offered_by": "Simplilearn",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "10hr 17min 11s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 26,
  "name": "The Foundations of Entrepreneurship",
  "link": "https://www.youtube.com/watch?v=UEngvxZ11sw",
  "domains": "Business",
  "description": "This entrepreneurship course will teach you the important lessons that they don'tn teach you in business school. You will learn about topics such as how ton network, how to find customers, and how to get a job.",
  "offered_by": "freeCodeCamp",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "5hr 46min 29s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 27,
  "name": "The Basics of Business Education",
  "link": "https://youtu.be/69dLyztc-As",
  "domains": "Business",
  "description": "Presentation at Dong-A University that every business student in the world nshould watch. What a business education is about. What a business studentn should study and learn. Common problems and mistakes in business programs. Common mistakes that students make",
  "offered_by": "Krassimir Petrov",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "57min 05s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 28,
  "name": "basics and fundamentals of human resource management",
  "link": "https://youtu.be/aA1OlFHZWtU",
  "domains": "Business",
  "description": "Basics and fundamentals of human resource management. the process of hiring nand developing employees so that they become more valuable to the organizationn. human resource management includes conducting job analyses, planningn staffing needs, recruiting the right people for the job, orientation and training,n managing wages and salaries, offering benefits benefits and incentives, nperformance appraisal, conflict resolution and communication with alln employees at all levels.",
  "offered_by": "selfLearn-en",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "44min 24s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 29,
  "name": "Big Data",
  "link": "https://youtu.be/CnQx2ke2KF8?list=PLlzSX_wxRm23EgvRJ9NlooM93uyxdUqvy",
  "domains": "Business",
  "description": "BIG DATA  Jean-Antoine MoreaunDroits d'auteur gérés par l'ADAGP",
  "offered_by": "Jean-Antoine Moreau",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "1hr 09min 07s",
  "number_of_videos": 43,
  "source": "Youtube"
 },
 {
  "id": 30,
  "name": "Cloud Computing Full course",
  "link": "https://youtu.be/-8O32k26RWA",
  "domains": "Technologie",
  "description": "Here's a 12-hour course on Cloud Computing! With the world being driven byn the developments in computing, Cloud Computing has become an extremelyn important factor in today’s constantly evolving technology, and that's whyn it's also a sought-after career option today. Cloud Computing is the deliveryn of computing services over the Internet. These include a variety of services,n such as storage, databases, intelligence, analytics, etc. and one pays only nfor the services they require on an on-the-go basis.",
  "offered_by": "Great Learning",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "11hr 33min 15s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 31,
  "name": "IT support Training",
  "link": "https://www.youtube.com/playlist?list=PLxo6mf-dQ33hxxhyQ2VctHlxAHnkhxcKL",
  "domains": "Technologie",
  "description": "",
  "offered_by": "Jobskillshare Community",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "6 days",
  "number_of_videos": 10,
  "source": "Youtube"
 },
 {
  "id": 32,
  "name": "Cyber Security",
  "link": "https://youtu.be/nzZkKoREEGo",
  "domains": "Technologie/Security",
  "description": "This video on Cyber Security Full Course  will help you understand andn learn the fundamentals of Cyber Security. This Cyber Security Tutorial isn ideal for both beginners as well as professionals who want to master the nCyber Security concepts.",
  "offered_by": "Edureka",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "08hr 21min 09s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 33,
  "name": "IT Skills",
  "link": "https://youtu.be/On6dsIp5yw0",
  "domains": "Business",
  "description": "IT Professional Skills Development Program",
  "offered_by": "Jobskillshare Community",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "11hr 54min 23s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 34,
  "name": "Professional Writing Skills",
  "link": "https://youtu.be/l7QfTE2vauU",
  "domains": "Business",
  "description": "",
  "offered_by": "Write It Well",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "28min 53s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 35,
  "name": "Basic Concept of Accounting",
  "link": "https://youtu.be/xWKfKCnQqAE",
  "domains": "Business",
  "description": "In this video I have explained the basic concept of accounting in a simple way and this is especially for science background students.",
  "offered_by": "Saheb Academy",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "33min 03s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 36,
  "name": "Introduction To Financial Management",
  "link": "https://youtu.be/U4LXk5lbTpI",
  "domains": "Business",
  "description": "",
  "offered_by": "Deric Business Class",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "11min 04s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 37,
  "name": "Introduction to Corporate Finance",
  "link": "https://youtu.be/5eGRi66iUfU",
  "domains": "Business",
  "description": "This  Intro to Corporate Finance Course will teach you who the key players inn the capital markets are, what the capital raising process looks like, the main nbusiness valuation techniques, types of valuation multiples, how to structuren an M&A deal, how to finance an acquisition, types of equity securities,n and an overview of career paths as well as how to prepare for interviews.",
  "offered_by": "Corporate Finance Institute",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "1hr 07min 40s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 38,
  "name": "Excel Crash Course for Finance Professionals",
  "link": "https://youtu.be/kjoldYi7eH0",
  "domains": "Business",
  "description": "Enroll in the FREE full course to earn your certification and advance yourn career: http://courses.corporatefinanceinstit...  The ultimate Excel crash ncourse for finance professionals.  Learn all the Excel tips, tricks, shortcuts,n formulas and functions you need for financial modeling in this free onlinen course.  Key concepts include: formatting, ribbon shortcuts, if statements, neomonth, year, paste special, fill right, fill down, auto sum, sumproduct,n iferror, today(), concatenate, special numbers, vlookup, index, match,n  xirr, xnpv, yearfrac, and much more.",
  "offered_by": "Corporate Finance Institute",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "1hr 15min 57s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 39,
  "name": "Agile Scrum",
  "link": "https://youtu.be/VFQtSqChlsk",
  "domains": "Business",
  "description": "In this Scrum Full Course video, we'll teach you everything you need to known about Agile and Scrum. We'll be covering topics like Scrum, Agile, Agile nProject Management, Agile User Stories, Scaled Agile Framework, hown Scrum, Kanban and Agile are different from one another and much more!n So, without further ado, let's jump right in!",
  "offered_by": "Simplilearn",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "3hr 24min 57s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 40,
  "name": "Artificial Intelligence Foundations: Machine Learning",
  "link": "https://www.linkedin.com/learning/artificial-intelligence-foundations-machine-learning",
  "domains": "Artificial Intelligence (AI)",
  "description": "Get the training you need to stay ahead with expert-led courses on Artificial Intelligence (AI).",
  "offered_by": "LinkedIn",
  "type": "Course",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "1hr 17min",
  "number_of_videos": 1,
  "source": "Linkedin"
 },
 {
  "id": 41,
  "name": "Artificial Intelligence for Business Leaders",
  "link": "https://www.linkedin.com/learning/artificial-intelligence-for-business-leaders",
  "domains": "Artificial Intelligence (AI)",
  "description": "stay ahead with expert-led courses on Artificial Intelligence (AI).",
  "offered_by": "LinkedIn",
  "type": "Course",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "1hr 33min",
  "number_of_videos": 1,
  "source": "Linkedin"
 },
{
  "id": 42,
  "name": "Machine Learning Foundations: Linear Algebra",
  "link": "https://www.linkedin.com/learning/machine-learning-foundations-linear-algebra",
  "domains": "Machine Learning",
  "description": "Get the training you need to stay ahead with expert-led courses on Machine Learning.",
  "offered_by": "LinkedIn",
  "type": "Course",
  "rating": 4.4,
  "difficulty": "Intermediate",
  "duration": "1hr 20min",
  "number_of_videos": 1,
  "source": "Linkedin"
 },
{
  "id": 43,
  "name": "Learning Cloud Computing: Core Concepts",
  "link": "https://www.linkedin.com/learning/learning-cloud-computing-core-concepts-13966302",
  "domains": "Cloud Computing",
  "description": "Get the training you need to stay ahead with expert-led courses on Cloud Computing.",
  "offered_by": "LinkedIn",
  "type": "Course",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "1hr 32min",
  "number_of_videos": 1,
  "source": "Linkedin"
 },
{
  "id": 44,
  "name": "Artificial intelligence",
  "link": "https://www.youtube.com/watch?v=JMUxmLyrhSk&pp=ugMICgJmchABGAE%3D",
  "domains": "Technologie/AI",
  "description": "This video on Artificial Intelligence will provide you with a complete and detailed knowledge of the concepts of Artificial Intelligence with practical examples.",
  "offered_by": "Édureka",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "4hr 52min 51s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 45,
  "name": "Digital Marketing",
  "link": "https://youtu.be/1p4c-5-4iAY",
  "domains": "Business/Digital marketing",
  "description": "Digital Marketing Course Tutorial",
  "offered_by": "MarketingFundas",
  "type": "Course",
  "rating": "",
  "difficulty": "Advanced",
  "duration": "34hr 06min 04s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 46,
  "name": "Project Advanced",
  "link": "https://youtu.be/1vzGD6igNSA",
  "domains": "Business/Project management",
  "description": "Who it's For: Microsoft Project is professional level software made for project managers, resource managers, team leads, and anyone who is given the task of planning and running a project that is too big for “I’ll just knock it out.”nnWhat it is: MS Project is a structure-based project planning, running, and tracking software tool. It is the most popular project management tool. Microsoft Project students will learn how to plan projects of any scope, small to large.nnWhat You'll Learn: People who learn MS Project start from the ground level and learn how to build a phase-based work breakdown structure, apply durations, constraints, resources, and how to track the project while it runs. You’ll learn tricks, tips, and how to modify Microsoft Project to fit your needs and work style.",
  "offered_by": "LearnitTraining",
  "type": "Course",
  "rating": "",
  "difficulty": "Advanced",
  "duration": "49min 15s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 47,
  "name": "Digital Communications",
  "link": "https://www.youtube.com/watch?v=4NYt34yNWqU&list=PLOzRYVm0a65dhUUuWow3dmimcgOisQn4I",
  "domains": "Business",
  "description": "Principles of Digital Communications",
  "offered_by": "IIT Bombay July",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "12 weeks",
  "number_of_videos": 65,
  "source": "Youtube"
 },
 {
  "id": 48,
  "name": "Machine Learning with Python",
  "link": "https://www.youtube.com/watch?v=RnFGwxJwx-0",
  "domains": "Technologie/ML",
  "description": "Machine learning is defined as the “use and development of computer systems that can learn and adapt without following explicit instructions, using algorithms and statistical models to analyze and draw inferences from patterns in data.”nGreat Learning’s python with Machine learning course brings you a full-fledged course inclusive of all essential topics like introduction to machine learning, machine learning algorithm, reinforcement learning, and many more. This course will enlighten you with machine learning concepts, not just conceptually but also with practicality.",
  "offered_by": "Great Learning",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "10hr 36min 31s",
  "source": "Youtube"
 },
 {
  "id": 49,
  "name": "Data Science",
  "link": "https://youtu.be/csG_qfOTvxw",
  "domains": "Business/Data",
  "description": "Hello All in this video we will understand how we can learn Data Science Smartly",
  "offered_by": "Krish Naik",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "12min 12s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 50,
  "name": "Excel 2019 Intro to Data Analysis",
  "link": "https://youtu.be/M6miEypg6Mo",
  "domains": "Business",
  "description": "What you'll learn: Beyond simple averages and totals, Microsoft Excel offersn many features to help you draw insights from your data. Sometimes those observations come from a particular formatting or visualization of the data; other times a specific summary function will generate a surprisingly significant result. In this full-length introductory course, learn all about data analytics in Excel with tools like table formatting, conditional functions, charting, pivot tables, and much more.",
  "offered_by": "LearnitTraining",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "1hr 32min 25s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 51,
  "name": "Power BI",
  "link": "https://www.youtube.com/playlist?list=PL1aYsXmhJ1WcRPx3gotG36pu-lb7YdmOa",
  "domains": "Business",
  "description": "In this training, you will develop a dashboard on the example of a company thatn sells textiles online, and this example will serve as a common thread in then practical implementation of the method.",
  "offered_by": "Alphorm",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "50min",
  "number_of_videos": 7,
  "source": "Youtube"
 },
 {
  "id": 52,
  "name": "Business analyst interview",
  "link": "https://youtu.be/N4kf3RQiryA",
  "domains": "Business",
  "description": "Business analyst interviews can be stressful, but there are things you can do to improve your chances of success. This is an example of how to perform well in answering the most common business analysis interview questions posed to senior business analysts.",
  "offered_by": "BA BLOCKS",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "26min 15s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 53,
  "name": "Agile Methodology",
  "link": "https://youtu.be/KNBHQ0pyaG8",
  "domains": "Business",
  "description": "This video on Agile Methodology Tutorial for Beginners explains the fundamentals of Agile methodology & its process. It also explains the history of Agile methodology and how it addresses the limitations of the Waterfall model.nAreas Covered:n1. Evolution of Agile Methodologyn2. Understanding Waterfall Model and Its Limitationsn3. Agile Manifeston4. Agile Values & Principlesn5. Introduction to Agilen6. Agile vs Waterfalln7. Advantages of Agilen8. Real Life Implementation of Agile Methodologyn9. Disadvantages of Agilen10. Components of Agile Methodologyn11. Agile Team Roles n12. Agile Process/ Lifecyclen13. Agile Metricsn14. Different Agile Methodologiesn15. Scaling Agilen16. Agile Best Practicesn17. 14th Annual State of Agile Report - Agile Trendsn18. Demo on Jiran19. Agile Methodology Training & Certifications",
  "offered_by": "Invensis Learning",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "1hr 22min 18s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 54,
  "name": "Advanced Reporting in Microsoft Project 2019",
  "link": "https://youtu.be/h7t8r2yz09w",
  "domains": "Business",
  "description": "In this Microsoft Project 2019 tutorial we look at some of the advanced reportingn features available in Microsoft Project. nThis is a summary video that takes you through the main reports available in nMS Project.",
  "offered_by": "Simon Sez IT",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "13min 25s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 55,
  "name": "Human resource management (HRM) explained",
  "link": "https://youtu.be/aPEUKLxxh_k",
  "domains": "Business",
  "description": "To fully understand how HRM can activate the business, we must first understand human resource management. Because there is so much more to human resource management than you might think. Join us as we take a closer look at this fascinating field, including:nn💡 What is HRMn💡 HRM activitiesn💡 Why HRM is essential for successful organizationsn💡 How to make an impact with human resource managementn💡 Future trends in HRM",
  "offered_by": "AIHR - Academy to Innovate HR",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "14min 47s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 56,
  "name": "AWS Tutorial",
  "link": "https://youtu.be/uQdzcIf_KII",
  "domains": "Technologie/System and network administration",
  "description": "This AWS tutorial for beginners will help you understand what is AWSn (Amazon Web Services), how did AWS become so successful, the servicesn that AWS provides (AWS EC2, Amazon Elastic Beanstalk, Amazon Lightsail,n Amazon Lambda, Amazon S3, Amazon red shift, amazon ecs, amazon route 53,n amazon vpc, aws cloudfront, aws sagemaker, aws autoscaling, and aws elastic nbeanstalk), the future of AWS and a demonstration on deploying, in the end nwe’ll also be discussing AWS certification and AWS interview questions forn beginners and advanced level.. This AWS tutorial video is suitable for thosen individuals who aspire to become AWS Certified Solution Architect. However,n let move ahead and understand what AWS actually is and what are the services nthat AWS provides to an organization.",
  "offered_by": "Simplilearn",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "10hr 56min 49s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 57,
  "name": "IT Help Desk Learning Guide and Job Assistance Complete",
  "link": "https://youtu.be/VN7IDVxoeCY",
  "domains": "Technologie/Help desk IT",
  "description": "This video is designed to prepare for Help Desk work. It's really easy to follow nand you will learn a lot.",
  "offered_by": "Cobuman",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "28min 35s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 58,
  "name": "HELP DESK/IT SUPPORT TECHNICAL TEST PREPARATION",
  "link": "https://youtu.be/HaZR5p8zzuQ",
  "domains": "Technologie/Help desk IT",
  "description": "This long video is for candidates applying for various technical support roles,n including help desk, desktop support technicians, and other IT support roles.n A good candidate for a Windows technical support job will be able to display nfamiliarity with basic windows ten administration and troubleshooting, basicn Active directory, and office 365 management skills.",
  "offered_by": "Jobskillshare Community",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "6hr 20min 03s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 59,
  "name": "Cybersecurity",
  "link": "https://youtu.be/agnDpN961xU",
  "domains": "Technologie/Security",
  "description": "This video tutorial on Cybersecurity for Beginners explains the fundamentals of cybersecurity in detail. You will learn what exactly is cybersecurity, different types of cybersecurity threats, and ways to avoid them. Listed below are the topics that will be discussed in detail:nnWhat is Cyber Security?nHistory of Hacking and SecuritynCIA TRIADnWhy Cyber Security?nElements of Network SecuritynTypes of Cyber AttacksnCase StudynBasic Practices and Methods to Avoid Cyber AttacksnJob Prospects and Market Trends in Cyber SecuritynRole of Cyber Security AnalystnTop 10 Cyber Security Certifications and Training",
  "offered_by": "Invensis Learning",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "28min 49s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 60,
  "name": "Soft Skills",
  "link": "https://youtu.be/ADJAcyTq1us",
  "domains": "Business",
  "description": "This tutorial is designed primarily for individuals stepping into the corporaten world. For the students in high school and University life. Also, for the nworking professionals and anyone who wants to work on their mannerismn in a social gathering.",
  "offered_by": "Tutorials Point",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "18min 18s",
  "number_of_videos": 1,
  "source": "Youtube"
 },
 {
  "id": 61,
  "name": "SAP SD (Sales & Distribution)",
  "link": "https://youtu.be/MNTEnpAtjvs",
  "domains": "Business",
  "description": "SAP Sales and Distribution (SD) is an important module of SAP ERPn consisting of business processes required in selling, shipping, billing nof a product. The module is tightly integrated with other SAP MM & nSAP PP. Key sub-modules of SAP SD are Customer and Vendor Master nData, Sales, Delivery, Billing, Pricing and Credit Management.",
  "offered_by": "SAP TUBE",
  "type": "Course",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "3hr 49min 37s",
  "number_of_videos": 1,
  "source": "Youtube"
 }
]
# for i in range(len(COURSES)):
#  print(COURSES[i]['name'])