cert_dict = [{
		"Name": "Google project management",
		"Link": "https://www.coursera.org/professional-certificates/google-project-management",
		"Domains": "Business/Leadership and Management",
		"Description": "In this program, you'll learn in-demand skills that will have you job-ready inn less than six months. No degree or experience is required.",
		"Offered by": "Google",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "6 months"
	},
	{
		"Name": "Meta media social markenting",
		"Link": "https://www.coursera.org/professional-certificates/facebook-social-median-marketing",
		"Domains": "Business/Marketing",
		"Description": "Develop professional skills for a sought-after career and earnn a diploma delivered by Meta. No prior degree or experience is required to get started.",
		"Offered by": "Meta",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "7 months"
	},
	{
		"Name": "Intuit bookeepping",
		"Link": "https://www.coursera.org/professional-certificates/intuit-bookkeeping",
		"Domains": "Business/Business basics",
		"Description": "Learn the professional skills you need to succeed in the accounting field.n No degree or previous experience is required.",
		"Offered by": "Intuit",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "4 months"
	},
	{
		"Name": "Meta-analyse markeying",
		"Link": "https://www.coursera.org/professional-certificates/facebook-marketing-analytics",
		"Domains": "Business/Marketing",
		"Description": "Build in-demand skills and gain credentials to go from beginner to job-readyn in 5 months or less. No degree or prior experience required.",
		"Offered by": "Meta",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "7 months"
	},
	{
		"Name": "AWS cloud solutions architect",
		"Link": "https://www.coursera.org/professional-certificates/aws-cloud-solutions-architect",
		"Domains": "Information technology",
		"Description": "Gain the skills and knowledge to design architectural solutions on AWS and prepare for your AWS Certified Solutions Architect - Associate exam.",
		"Offered by": "AWS",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "4 months"
	},
	{
		"Name": "Certification Azure Data Scientist nAssociate de Microsoft (DP-100)",
		"Link": "https://www.coursera.org/professional-certificates/azure-data-scientist",
		"Domains": "IT/Software development",
		"Description": "Apply data science and machine learning to implement and run machine learning workloads on Azure.",
		"Offered by": "Microsoft",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Intermediate",
		"Duration": "7 months"
	},
	{
		"Name": "Certification Cloud developer",
		"Link": "https://www.coursera.org/professional-certificates/google-cloud-developer",
		"Domains": "Information technology/Cloud Computing",
		"Description": "Developer Best Practices on Google Cloud",
		"Offered by": "Google Cloud",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Intermediate",
		"Duration": "2 months"
	},
	{
		"Name": "Developer TensorFlow",
		"Link": "https://www.coursera.org/professional-certificates/tensorflow-in-practice",
		"Domains": "Data Science/Machine learning",
		"Description": "",
		"Offered by": "DeepLearning.AI",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Intermediate",
		"Duration": "4 months"
	},
	{
		"Name": "Azure Developer Associate den Microsoft (AZ-204)",
		"Link": "https://www.coursera.org/professional-certificates/azure-developer-associate",
		"Domains": "Data Science/Machine learning",
		"Description": "Learn how to create end-to-end solutions in Microsoft Azure",
		"Offered by": "Microsoft",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Intermediate",
		"Duration": "10 months"
	},
	{
		"Name": "Azure Data Engineer Associate de Microsoft (DP-203)",
		"Link": "https://www.coursera.org/professional-certificates/microsoft-azure-dp-203-data-engineering",
		"Domains": "Data Science/Data analys",
		"Description": "Master designing and implementing data solutions that use Microsoft Azure ndata services",
		"Offered by": "Microsoft",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Intermediate",
		"Duration": "13 months"
	},
	{
		"Name": "Google Professional Workspace Administrator",
		"Link": "https://www.coursera.org/professional-certificates/g-suite-administration",
		"Domains": "IT/Computer and network security",
		"Description": "",
		"Offered by": "Google Cloud",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "2 months"
	},
	{
		"Name": "Google Cloud Digital Leader",
		"Link": "https://www.coursera.org/professional-certificates/google-cloud-digital-leader-training",
		"Domains": "Information technology/Cloud Computing",
		"Description": "Build your confidence in the cloud domain so you can talk with colleagues in technical cloud positions and contribute to informed cloud-related business decisions.",
		"Offered by": "Google Cloud",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "1 month"
	},
	{
		"Name": "Cybersecurity with Palo Alto Networks",
		"Link": "https://www.coursera.org/professional-certificates/palo-alto-networks-cybersecurity-fundamentals",
		"Domains": "Information technology/Security",
		"Description": "Acquire entry-level cybersecurity skills as per NIST/NICE requirements for staff roles.",
		"Offered by": "Paloalto",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "6 months"
	},
	{
		"Name": "Data Science Specialist",
		"Link": "https://www.coursera.org/professional-certificates/certified-data-science-practitioner",
		"Domains": "Data Science/Data analys",
		"Description": "Master strategies to implement Data Science techniques in order to solve business problems.",
		"Offered by": "CERTNEXUS",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Intermediate",
		"Duration": "6 months"
	},
	{
		"Name": "CertNexus Ethics Certified Emerging Technologist",
		"Link": "https://www.coursera.org/professional-certificates/certified-ethical-emerging-technologist",
		"Domains": "Data Science/Machine learning",
		"Description": "Master strategies that put ethics into practice in data-driven technologies like Artificial Intelligence, Data Science, and the Internet of Things.",
		"Offered by": "CERTNEXUS",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "8 months"
	},
	{
		"Name": "UCI Project Management",
		"Link": "https://www.coursera.org/professional-certificates/applied-project-management",
		"Domains": "Business/Leadership and Management",
		"Description": "",
		"Offered by": "UCI",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "6 months"
	},
	{
		"Name": "Cloud Devops engineer",
		"Link": "https://www.coursera.org/professional-certificates/sre-devops-engineer-google-cloud",
		"Domains": "Information technology/Cloud Computing",
		"Description": "",
		"Offered by": "Google Cloud",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "5 months"
	},
	{
		"Name": "User experience design",
		"Link": "https://www.coursera.org/professional-certificates/google-ux-design",
		"Domains": "IT/design and product",
		"Description": "In this program, you’ll learn in-demand skills that will have you job-ready in less than 6 months. No degree or experience required.",
		"Offered by": "Google",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "6 months"
	},
	{
		"Name": "DevOps and software engineering",
		"Link": "https://www.coursera.org/professional-certificates/devops-and-software-engineering",
		"Domains": "IT/Software development",
		"Description": "Master DevOps, Agile, Scrum, CI/CD and Cloud Native with hands-on job-ready skills.",
		"Offered by": "IBM",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "15 months"
	},
	{
		"Name": "Machine Learning for Analytics",
		"Link": "https://www.coursera.org/mastertrack/machine-learning-analytics-chicago",
		"Domains": "Data Science/Machine learning",
		"Description": "In this 4-course program, you'll develop skills in statistics and machine learning by practicing on real-world data and real-world applications. Advance your career as a data science professional.",
		"Offered by": "The university of Chicago",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "7 months"
	},
    {
		"Name": "Oracle Cloud Infrastructure",
		"Link": "https://mylearn.oracle.com/learning-path/become-an-oci-foundations-associate/108448",
		"Domains": "Cloud Infrastructure",
		"Description": "This Learning Path provides the foundational knowledge of Oracle Cloud Infrastructure Cloud Services, and prepares you for the Oracle Cloud Infrastructure Foundations Associate Certification.nnGet your Oracle Free Tier account and perform Hands-On Labs.nnLatest updates and new features are included on an ongoing basis to keep the content current.",
		"Offered by": "Oracle",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "11hr"
	},
	{
		"Name": "Global Human Resources",
		"Link": "https://mylearn.oracle.com/learning-path/become-a-certified-global-human-resources-core-hr-implementer/57291",
		"Domains": "Human Resources",
		"Description": "This Learning Path consists of key courses that will help in your preparation to obtain an Oracle Global Human Resources Cloud:Core HR Implementation certification credential.nnAn Oracle Global Human Resources Cloud: Core HR Implementation Certification credential provides a strong foundation and expertise in selling or implementing Human Resource Cloud: Core HR. nnUse this Learning Path to understand the key concepts and processes involved in implementing Core HR and to prepare to take and pass the related certification exam.",
		"Offered by": "Oracle",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "36hr"
	},
	{
		"Name": "Business Analytics Expert",
		"Link": "https://mylearn.oracle.com/learning-path/become-a-business-analytics-expert/91371",
		"Domains": "Business Analysis",
		"Description": "In this Learning Path, you will learn how to gain insight into your data with Oracle Analytics Cloud. You will learn four distinct skills that will equip you to perform strategic Business Analytics effectively:nnCreate analyses and dashboards, load and model data, and configure Business Intelligence Cloud Service on mobile.nCollect, Merge, and Visualize data using Oracle Analytics CloudnUse Machine Learning and Augmented Analytics to gain a faster and better prescriptive solutions and actionable business intelligence.nCreate highly formatted document for analysis using Pixel Perfect ReportnEnhance your knowledge with hands-on labs.nnThis Learning Path prepares you for the Oracle Cloud Platform Enterprise Analytics Professional Certification.",
		"Offered by": "Oracle",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "Beginner",
		"Duration": "39hr"
	},
	{
		"Name": "Oracle DB Admin 2019",
		"Link": "https://mylearn.oracle.com/learning-path/earn-the-oracle-db-admin-2019-certified-professional-credential-cn/84229",
		"Domains": "Data",
		"Description": "This Learning Path consists of key courses that will help in your preparation to obtain an Oracle Database Administration 2019 Certified Professional credential (Available only in China).",
		"Offered by": "Oracle",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "All",
		"Duration": "88hr"
	},
	{
		"Name": "Cloud data management",
		"Link": "https://mylearn.oracle.com/learning-path/become-a-data-management-foundations-associate-oci-exam-subscription/111227",
		"Domains": "Data",
		"Description": "Become a Data Management Foundations Associate (OCI Exam Subscription)",
		"Offered by": "Oracle",
		"Type": "Certification",
		"Rating": "",
		"Difficulty": "All",
		"Duration": "1hr 30min"
	}
]