COURSES = [
 {
  "id": 1,
  "name": "Oracle Cloud Infrastructure",
  "link": "https://mylearn.oracle.com/learning-path/become-an-oci-foundations-associate/108448",
  "domains": "Cloud Infrastructure",
  "description": "This Learning Path provides the foundational knowledge of Oracle Cloud Infrastructure Cloud Services, and prepares you for the Oracle Cloud Infrastructure Foundations Associate Certification.nnGet your Oracle Free Tier account and perform Hands-On Labs.nnLatest updates and new features are included on an ongoing basis to keep the content current.",
  "offered_by": "Oracle",
  "type": "Certification",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "11hr",
  "number_of_videos": "",
  "source": "Oracle"
 },
 {
  "id": 2,
  "name": "Global Human Resources",
  "link": "https://mylearn.oracle.com/learning-path/become-a-certified-global-human-resources-core-hr-implementer/57291",
  "domains": "Human Resources",
  "description": "This Learning Path consists of key courses that will help in your preparation to obtain an Oracle Global Human Resources Cloud:Core HR Implementation certification credential.nnAn Oracle Global Human Resources Cloud: Core HR Implementation Certification credential provides a strong foundation and expertise in selling or implementing Human Resource Cloud: Core HR. nnUse this Learning Path to understand the key concepts and processes involved in implementing Core HR and to prepare to take and pass the related certification exam.",
  "offered_by": "Oracle",
  "type": "Certification",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "36hr",
  "number_of_videos": "",
  "source": "Oracle"
 },
 {
  "id": 3,
  "name": "Business Analytics Expert",
  "link": "https://mylearn.oracle.com/learning-path/become-a-business-analytics-expert/91371",
  "domains": "Business Analysis",
  "description": "In this Learning Path, you will learn how to gain insight into your data with Oracle Analytics Cloud. You will learn four distinct skills that will equip you to perform strategic Business Analytics effectively:nnCreate analyses and dashboards, load and model data, and configure Business Intelligence Cloud Service on mobile.nCollect, Merge, and Visualize data using Oracle Analytics CloudnUse Machine Learning and Augmented Analytics to gain a faster and better prescriptive solutions and actionable business intelligence.nCreate highly formatted document for analysis using Pixel Perfect ReportnEnhance your knowledge with hands-on labs.nnThis Learning Path prepares you for the Oracle Cloud Platform Enterprise Analytics Professional Certification.",
  "offered_by": "Oracle",
  "type": "Certification",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "39hr",
  "number_of_videos": "",
  "source": "Oracle"
 },
 {
  "id": 4,
  "name": "Oracle DB Admin 2019",
  "link": "https://mylearn.oracle.com/learning-path/earn-the-oracle-db-admin-2019-certified-professional-credential-cn/84229",
  "domains": "Data",
  "description": "This Learning Path consists of key courses that will help in your preparation to obtain an Oracle Database Administration 2019 Certified Professional credential (Available only in China).",
  "offered_by": "Oracle",
  "type": "Certification",
  "rating": "",
  "difficulty": "All",
  "duration": "88hr",
  "number_of_videos": "",
  "source": "Oracle"
 },
 {
  "id": 5,
  "name": "Cloud data management",
  "link": "https://mylearn.oracle.com/learning-path/become-a-data-management-foundations-associate-oci-exam-subscription/111227",
  "domains": "Data",
  "description": "Become a Data Management Foundations Associate (OCI Exam Subscription)",
  "offered_by": "Oracle",
  "type": "Certification",
  "rating": "",
  "difficulty": "All",
  "duration": "1hr 30min",
  "number_of_videos": "",
  "source": "Oracle"
 },
 {
  "id": 6,
  "name": "Google project management",
  "link": "https://www.coursera.org/professional-certificates/google-project-management",
  "domains": "Business/Leadership and Management",
  "description": "In this program, you'll learn in-demand skills that will have you job-ready inn less than six months. No degree or experience is required.",
  "offered_by": "Google",
  "type": "Certification",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 7,
  "name": "Meta media social markenting",
  "link": "https://www.coursera.org/professional-certificates/facebook-social-median-marketing",
  "domains": "Business/Marketing",
  "description": "Develop professional skills for a sought-after career and earnn a diploma delivered by Meta. No prior degree or experience is required to get started.",
  "offered_by": "Meta",
  "type": "Certification",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "7 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 8,
  "name": "Intuit bookeepping",
  "link": "https://www.coursera.org/professional-certificates/intuit-bookkeeping",
  "domains": "Business/Business basics",
  "description": "Learn the professional skills you need to succeed in the accounting field.n No degree or previous experience is required.",
  "offered_by": "Intuit",
  "type": "Certification",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "4 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 9,
  "name": "Meta-analyse markeying",
  "link": "https://www.coursera.org/professional-certificates/facebook-marketing-analytics",
  "domains": "Business/Marketing",
  "description": "Build in-demand skills and gain credentials to go from beginner to job-readyn in 5 months or less. No degree or prior experience required.",
  "offered_by": "Meta",
  "type": "Certification",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "7 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 10,
  "name": "AWS cloud solutions architect",
  "link": "https://www.coursera.org/professional-certificates/aws-cloud-solutions-architect",
  "domains": "Information technology",
  "description": "Gain the skills and knowledge to design architectural solutions on AWS and prepare for your AWS Certified Solutions Architect - Associate exam.",
  "offered_by": "AWS",
  "type": "Certification",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "4 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 11,
  "name": "Certification Azure Data Scientist nAssociate de Microsoft (DP-100)",
  "link": "https://www.coursera.org/professional-certificates/azure-data-scientist",
  "domains": "IT/Software development",
  "description": "Apply data science and machine learning to implement and run machine learning workloads on Azure.",
  "offered_by": "Microsoft",
  "type": "Certification",
  "rating": 4.6,
  "difficulty": "Intermediate",
  "duration": "7 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 12,
  "name": "Certification Cloud developer",
  "link": "https://www.coursera.org/professional-certificates/google-cloud-developer",
  "domains": "Information technology/Cloud Computing",
  "description": "Developer Best Practices on Google Cloud",
  "offered_by": "Google Cloud",
  "type": "Certification",
  "rating": 4.9,
  "difficulty": "Intermediate",
  "duration": "2 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 13,
  "name": "Developer TensorFlow",
  "link": "https://www.coursera.org/professional-certificates/tensorflow-in-practice",
  "domains": "Data Science/Machine learning",
  "offered_by": "DeepLearning.AI",
  "type": "Certification",
  "rating": 4.5,
  "difficulty": "Intermediate",
  "duration": "4 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 14,
  "name": "Azure Developer Associate den Microsoft (AZ-204)",
  "link": "https://www.coursera.org/professional-certificates/azure-developer-associate",
  "domains": "Data Science/Machine learning",
  "description": "Learn how to create end-to-end solutions in Microsoft Azure",
  "offered_by": "Microsoft",
  "type": "Certification",
  "rating": 4.6,
  "difficulty": "Intermediate",
  "duration": "10 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 15,
  "name": "Azure Data Engineer Associate de Microsoft (DP-203)",
  "link": "https://www.coursera.org/professional-certificates/microsoft-azure-dp-203-data-engineering",
  "domains": "Data Science/Data analys",
  "description": "Master designing and implementing data solutions that use Microsoft Azure ndata services",
  "offered_by": "Microsoft",
  "type": "Certification",
  "rating": 4.5,
  "difficulty": "Intermediate",
  "duration": "13 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 16,
  "name": "Google Professional Workspace Administrator",
  "link": "https://www.coursera.org/professional-certificates/g-suite-administration",
  "domains": "IT/Computer and network security",
  "offered_by": "Google Cloud",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "2 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 17,
  "name": "Google Cloud Digital Leader",
  "link": "https://www.coursera.org/professional-certificates/google-cloud-digital-leader-training",
  "domains": "Information technology/Cloud Computing",
  "description": "Build your confidence in the cloud domain so you can talk with colleagues in technical cloud positions and contribute to informed cloud-related business decisions.",
  "offered_by": "Google Cloud",
  "type": "Certification",
  "rating": 4.6,
  "difficulty": "Beginner",
  "duration": "1 month",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 18,
  "name": "Cybersecurity with Palo Alto Networks",
  "link": "https://www.coursera.org/professional-certificates/palo-alto-networks-cybersecurity-fundamentals",
  "domains": "Information technology/Security",
  "description": "Acquire entry-level cybersecurity skills as per NIST/NICE requirements for staff roles.",
  "offered_by": "Paloalto",
  "type": "Certification",
  "rating": 4.6,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 19,
  "name": "Data Science Specialist",
  "link": "https://www.coursera.org/professional-certificates/certified-data-science-practitioner",
  "domains": "Data Science/Data analys",
  "description": "Master strategies to implement Data Science techniques in order to solve business problems.",
  "offered_by": "CERTNEXUS",
  "type": "Certification",
  "rating": 4.6,
  "difficulty": "Intermediate",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 20,
  "name": "CertNexus Ethics Certified Emerging Technologist",
  "link": "https://www.coursera.org/professional-certificates/certified-ethical-emerging-technologist",
  "domains": "Data Science/Machine learning",
  "description": "Master strategies that put ethics into practice in data-driven technologies like Artificial Intelligence, Data Science, and the Internet of Things.",
  "offered_by": "CERTNEXUS",
  "type": "Certification",
  "rating": 4.6,
  "difficulty": "Beginner",
  "duration": "8 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 21,
  "name": "UCI Project Management",
  "link": "https://www.coursera.org/professional-certificates/applied-project-management",
  "domains": "Business/Leadership and Management",
  "offered_by": "UCI",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 22,
  "name": "Cloud Devops engineer",
  "link": "https://www.coursera.org/professional-certificates/sre-devops-engineer-google-cloud",
  "domains": "Information technology/Cloud Computing",
  "offered_by": "Google Cloud",
  "type": "Certification",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "5 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 23,
  "name": "User experience design",
  "link": "https://www.coursera.org/professional-certificates/google-ux-design",
  "domains": "IT/design and product",
  "description": "In this program, you’ll learn in-demand skills that will have you job-ready in less than 6 months. No degree or experience required.",
  "offered_by": "Google",
  "type": "Certification",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 24,
  "name": "DevOps and software engineering",
  "link": "https://www.coursera.org/professional-certificates/devops-and-software-engineering",
  "domains": "IT/Software development",
  "description": "Master DevOps, Agile, Scrum, CI/CD and Cloud Native with hands-on job-ready skills.",
  "offered_by": "IBM",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "15 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 25,
  "name": "Machine Learning for Analytics",
  "link": "https://www.coursera.org/mastertrack/machine-learning-analytics-chicago",
  "domains": "Data Science/Machine learning",
  "description": "In this 4-course program, you'll develop skills in statistics and machine learning by practicing on real-world data and real-world applications. Advance your career as a data science professional.",
  "offered_by": "The university of Chicago",
  "type": "Certification",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "7 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 26,
  "name": "Oracle Cloud Infrastructure",
  "link": "https://mylearn.oracle.com/learning-path/become-an-oci-foundations-associate/108448",
  "domains": "Cloud Infrastructure",
  "description": "This Learning Path provides the foundational knowledge of Oracle Cloud Infrastructure Cloud Services, and prepares you for the Oracle Cloud Infrastructure Foundations Associate Certification.nnGet your Oracle Free Tier account and perform Hands-On Labs.nnLatest updates and new features are included on an ongoing basis to keep the content current.",
  "offered_by": "Oracle",
  "type": "Certification",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "11hr",
  "number_of_videos": 2,
  "source": "Oracle"
 },
 {
  "id": 27,
  "name": "Global Human Resources",
  "link": "https://mylearn.oracle.com/learning-path/become-a-certified-global-human-resources-core-hr-implementer/57291",
  "domains": "Human Resources",
  "description": "This Learning Path consists of key courses that will help in your preparation to obtain an Oracle Global Human Resources Cloud:Core HR Implementation certification credential.nnAn Oracle Global Human Resources Cloud: Core HR Implementation Certification credential provides a strong foundation and expertise in selling or implementing Human Resource Cloud: Core HR. nnUse this Learning Path to understand the key concepts and processes involved in implementing Core HR and to prepare to take and pass the related certification exam.",
  "offered_by": "Oracle",
  "type": "Certification",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "36hr",
  "number_of_videos": 1,
  "source": "Oracle"
 },
 {
  "id": 28,
  "name": "Business Analytics Expert",
  "link": "https://mylearn.oracle.com/learning-path/become-a-business-analytics-expert/91371",
  "domains": "Business Analysis",
  "description": "In this Learning Path, you will learn how to gain insight into your data with Oracle Analytics Cloud. You will learn four distinct skills that will equip you to perform strategic Business Analytics effectively:nnCreate analyses and dashboards, load and model data, and configure Business Intelligence Cloud Service on mobile.nCollect, Merge, and Visualize data using Oracle Analytics CloudnUse Machine Learning and Augmented Analytics to gain a faster and better prescriptive solutions and actionable business intelligence.nCreate highly formatted document for analysis using Pixel Perfect ReportnEnhance your knowledge with hands-on labs.nnThis Learning Path prepares you for the Oracle Cloud Platform Enterprise Analytics Professional Certification.",
  "offered_by": "Oracle",
  "type": "Certification",
  "rating": "",
  "difficulty": "Beginner",
  "duration": "39hr",
  "number_of_videos": 1,
  "source": "Oracle"
 },
 {
  "id": 29,
  "name": "Oracle DB Admin 2019",
  "link": "https://mylearn.oracle.com/learning-path/earn-the-oracle-db-admin-2019-certified-professional-credential-cn/84229",
  "domains": "Data",
  "description": "This Learning Path consists of key courses that will help in your preparation to obtain an Oracle Database Administration 2019 Certified Professional credential (Available only in China).",
  "offered_by": "Oracle",
  "type": "Certification",
  "rating": "",
  "difficulty": "All",
  "duration": "88hr",
  "number_of_videos": 1,
  "source": "Oracle"
 },
 {
  "id": 30,
  "name": "Cloud data management",
  "link": "https://mylearn.oracle.com/learning-path/become-a-data-management-foundations-associate-oci-exam-subscription/111227",
  "domains": "Data",
  "description": "Become a Data Management Foundations Associate (OCI Exam Subscription)",
  "offered_by": "Oracle",
  "type": "Certification",
  "rating": "",
  "difficulty": "All",
  "duration": "1hr 30min",
  "number_of_videos": 1,
  "source": "Oracle"
 },
 {
  "id": 31,
  "name": "Google Data Analytics Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/google-data-analytics",
  "domains": "Data Science",
  "description": "Data analytics is the collection, transformation, and organization of data in order to draw conclusions, make predictions, and drive informed decision making. ",
  "offered_by": "Google",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 32,
  "name": "Google Project Management: Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/google-project-management",
  "domains": "Busness",
  "description": "Project managers are natural problem-solvers. They set the plan and guide teammates, and manage changes, risks, and stakeholders.",
  "offered_by": "Google",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 33,
  "name": "Google UX Design Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/google-ux-design",
  "domains": "Computer Science",
  "description": "User experience (UX) designers focus on the interaction that users have with products, like websites, apps, and physical objects. They make those everyday interactions useful, enjoyable, and accessible.",
  "offered_by": "Google",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 34,
  "name": "Google IT Support Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/google-it-support",
  "offered_by": "Google",
  "type": "Certification",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 35,
  "name": "Google Digital Marketing & E-commerce Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce",
  "offered_by": "Google",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 36,
  "name": "HubSpot Sales Representative Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/hubspot-sales-representative",
  "offered_by": "HubSpot Academy",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 37,
  "name": "IBM Data Science Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/ibm-data-science",
  "offered_by": "IBM Skills Network",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "3 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 38,
  "name": "IBM Data Analyst Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/ibm-data-analyst",
  "offered_by": "IBM Skills Network",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "3 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 39,
  "name": "IBM Cybersecurity Analyst Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/ibm-cybersecurity-analyst",
  "offered_by": "IBM Skills Network",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "8 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 40,
  "name": "IBM Full Stack Software Developer Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/ibm-full-stack-cloud-developer",
  "offered_by": "IBM Skills Network",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "9 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 41,
  "name": "IBM Data Engineering Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/ibm-data-engineer",
  "offered_by": "IBM Skills Network",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "7 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 42,
  "name": "IBM Data Analytics with Excel and R Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/ibm-data-analyst-r-excel",
  "offered_by": "IBM Skills Network",
  "type": "Certification",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 43,
  "name": "IBM DevOps and Software Engineering Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/devops-and-software-engineering",
  "offered_by": "IBM Skills Network",
  "type": "Certification",
  "rating": 4.6,
  "difficulty": "Beginner",
  "duration": "9 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 44,
  "name": "IBM Technical Support  Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/ibm-technical-support",
  "offered_by": "IBM Skills Network",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "7 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 45,
  "name": "IBM Data Warehouse Engineer Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/data-warehouse-engineering",
  "offered_by": "IBM Skills Network",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "8 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 46,
  "name": "Intuit Bookkeeping Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/intuit-bookkeeping",
  "offered_by": "Intuit",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "4 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 47,
  "name": "Meta Social Media Marketing Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/facebook-social-media-marketing",
  "offered_by": "Meta",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 48,
  "name": "Meta Front-End Developer Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/meta-front-end-developer",
  "offered_by": "Meta",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "7 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 49,
  "name": "Meta Back-End Developer Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/meta-back-end-developer",
  "offered_by": "Meta",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "8 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 50,
  "name": "Meta Marketing Analytics Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/facebook-marketing-analytics",
  "offered_by": "Meta",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 51,
  "name": "Meta Database Engineer Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/meta-database-engineer",
  "offered_by": "Meta",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "6 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 52,
  "name": "Meta iOS Developer Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/meta-ios-developer",
  "offered_by": "Meta",
  "type": "Certification",
  "rating": 4.7,
  "difficulty": "Beginner",
  "duration": "8 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 53,
  "name": "Meta Android Developer Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/meta-android-developer",
  "offered_by": "Meta",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "8 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 54,
  "name": "PwC GST Taxation Executive  Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/pwc-gst-taxation-executive",
  "offered_by": "PwC India",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "3 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 55,
  "name": "Salesforce Sales Operations Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/salesforce-sales-operations",
  "offered_by": "Salesforce",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "4 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 56,
  "name": "Salesforce Sales Development Representative Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/sales-development-representative",
  "offered_by": "Salesforce",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "5 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 57,
  "name": "SAP Technology Consultant  Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/sap-technology-consultant",
  "offered_by": "SAP",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "7 months",
  "number_of_videos": "",
  "source": "Coursera"
 },
 {
  "id": 58,
  "name": "Tally Bookkeeper Professional Certificate",
  "link": "https://www.coursera.org/professional-certificates/tally-bookkeeper",
  "offered_by": "Tally Education",
  "type": "Certification",
  "rating": 4.8,
  "difficulty": "Beginner",
  "duration": "5 months",
  "number_of_videos": "",
  "source": "Coursera"
 }
]